# Data
data = {
  # Lists of Kunos-made assets
  'kunos-assets': {
    # Cars
    'cars': [
      'abarth500',
      'abarth500_s1',
      'alfa_romeo_giulietta_qv',
      'alfa_romeo_giulietta_qv_le',
      'bmw_1m',
      'bmw_1m_s3',
      'bmw_m3_e30',
      'bmw_m3_e30_drift',
      'bmw_m3_e30_dtm',
      'bmw_m3_e30_gra',
      'bmw_m3_e30_s1',
      'bmw_m3_e92',
      'bmw_m3_e92_drift',
      'bmw_m3_e92_s1',
      'bmw_m3_gt2',
      'bmw_z4',
      'bmw_z4_drift',
      'bmw_z4_gt3',
      'bmw_z4_s1',
      'ferrari_312t',
      'ferrari_458',
      'ferrari_458_gt2',
      'ferrari_458_s3',
      'ferrari_599xxevo',
      'ferrari_f40',
      'ferrari_f40_s3',
      'ferrari_laferrari',
      'ks_abarth500_assetto_corse',
      'ks_abarth_595ss',
      'ks_abarth_595ss_s1',
      'ks_abarth_595ss_s2',
      'ks_alfa_33_stradale',
      'ks_alfa_giulia_qv',
      'ks_alfa_mito_qv',
      'ks_alfa_romeo_155_v6',
      'ks_alfa_romeo_4c',
      'ks_alfa_romeo_gta',
      'ks_audi_a1s1',
      'ks_audi_r18_etron_quattro',
      'ks_audi_r8_lms',
      'ks_audi_r8_lms_2016',
      'ks_audi_r8_plus',
      'ks_audi_sport_quattro',
      'ks_audi_sport_quattro_rally',
      'ks_audi_sport_quattro_s1',
      'ks_audi_tt_cup',
      'ks_audi_tt_vln',
      'ks_bmw_m235i_racing',
      'ks_bmw_m4',
      'ks_bmw_m4_akrapovic',
      'ks_corvette_c7_stingray',
      'ks_corvette_c7r',
      'ks_ferrari_250_gto',
      'ks_ferrari_288_gto',
      'ks_ferrari_312_67',
      'ks_ferrari_330_p4',
      'ks_ferrari_488_challenge_evo',
      'ks_ferrari_488_gt3',
      'ks_ferrari_488_gt3_2020',
      'ks_ferrari_488_gtb',
      'ks_ferrari_812_superfast',
      'ks_ferrari_f138',
      'ks_ferrari_f2004',
      'ks_ferrari_fxx_k',
      'ks_ferrari_sf15t',
      'ks_ferrari_sf70h',
      'ks_ford_escort_mk1',
      'ks_ford_gt40',
      'ks_ford_mustang_2015',
      'ks_glickenhaus_scg003',
      'ks_lamborghini_aventador_sv',
      'ks_lamborghini_countach',
      'ks_lamborghini_countach_s1',
      'ks_lamborghini_gallardo_sl',
      'ks_lamborghini_gallardo_sl_s3',
      'ks_lamborghini_huracan_gt3',
      'ks_lamborghini_huracan_performante',
      'ks_lamborghini_huracan_st',
      'ks_lamborghini_miura_sv',
      'ks_lamborghini_sesto_elemento',
      'ks_lotus_25',
      'ks_lotus_3_eleven',
      'ks_lotus_72d',
      'ks_maserati_250f_12cyl',
      'ks_maserati_250f_6cyl',
      'ks_maserati_alfieri',
      'ks_maserati_gt_mc_gt4',
      'ks_maserati_levante',
      'ks_maserati_mc12_gt1',
      'ks_maserati_quattroporte',
      'ks_mazda_787b',
      'ks_mazda_miata',
      'ks_mazda_mx5_cup',
      'ks_mazda_mx5_nd',
      'ks_mazda_rx7_spirit_r',
      'ks_mazda_rx7_tuned',
      'ks_mclaren_570s',
      'ks_mclaren_650_gt3',
      'ks_mclaren_f1_gtr',
      'ks_mclaren_p1',
      'ks_mclaren_p1_gtr',
      'ks_mercedes_190_evo2',
      'ks_mercedes_amg_gt3',
      'ks_mercedes_c9',
      'ks_nissan_370z',
      'ks_nissan_gtr',
      'ks_nissan_gtr_gt3',
      'ks_nissan_skyline_r34',
      'ks_pagani_huayra_bc',
      'ks_porsche_718_boxster_s',
      'ks_porsche_718_boxster_s_pdk',
      'ks_porsche_718_cayman_s',
      'ks_porsche_718_spyder_rs',
      'ks_porsche_908_lh',
      'ks_porsche_911_carrera_rsr',
      'ks_porsche_911_gt1',
      'ks_porsche_911_gt3_cup_2017',
      'ks_porsche_911_gt3_r_2016',
      'ks_porsche_911_gt3_rs',
      'ks_porsche_911_r',
      'ks_porsche_911_rsr_2017',
      'ks_porsche_917_30',
      'ks_porsche_917_k',
      'ks_porsche_918_spyder',
      'ks_porsche_919_hybrid_2015',
      'ks_porsche_919_hybrid_2016',
      'ks_porsche_935_78_moby_dick',
      'ks_porsche_962c_longtail',
      'ks_porsche_962c_shorttail',
      'ks_porsche_991_carrera_s',
      'ks_porsche_991_turbo_s',
      'ks_porsche_cayenne',
      'ks_porsche_cayman_gt4_clubsport',
      'ks_porsche_cayman_gt4_std',
      'ks_porsche_macan',
      'ks_porsche_panamera',
      'ks_praga_r1',
      'ks_ruf_rt12r',
      'ks_ruf_rt12r_awd',
      'ks_toyota_ae86',
      'ks_toyota_ae86_drift',
      'ks_toyota_ae86_tuned',
      'ks_toyota_celica_st185',
      'ks_toyota_gt86',
      'ks_toyota_supra_mkiv',
      'ks_toyota_supra_mkiv_drift',
      'ks_toyota_supra_mkiv_tuned',
      'ks_toyota_ts040',
      'ktm_xbow_r',
      'lotus_2_eleven',
      'lotus_2_eleven_gt4',
      'lotus_49',
      'lotus_98t',
      'lotus_elise_sc',
      'lotus_elise_sc_s1',
      'lotus_elise_sc_s2',
      'lotus_evora_gtc',
      'lotus_evora_gte',
      'lotus_evora_gte_carbon',
      'lotus_evora_gx',
      'lotus_evora_s',
      'lotus_evora_s_s2',
      'lotus_exige_240',
      'lotus_exige_240_s3',
      'lotus_exige_s',
      'lotus_exige_s_roadster',
      'lotus_exige_scura',
      'lotus_exige_v6_cup',
      'lotus_exos_125',
      'lotus_exos_125_s1',
      'mclaren_mp412c',
      'mclaren_mp412c_gt3',
      'mercedes_sls',
      'mercedes_sls_gt3',
      'p4-5_2011',
      'pagani_huayra',
      'pagani_zonda_r',
      'ruf_yellowbird',
      'shelby_cobra_427sc',
      'tatuusfa1',
    ],
    # Tracks
    'tracks': [
      'drift',
      'imola',
      'ks_barcelona',
      'ks_black_cat_county',
      'ks_brands_hatch',
      'ks_drag',
      'ks_highlands',
      'ks_laguna_seca',
      'ks_monza66',
      'ks_nordschleife',
      'ks_nurburgring',
      'ks_red_bull_ring',
      'ks_silverstone',
      'ks_silverstone1967',
      'ks_vallelunga',
      'ks_zandvoort',
      'magione',
      'monza',
      'mugello',
      'spa',
      'trento-bondone',
    ],
    # Weather
    'weather': [
      '1_heavy_fog',
      '2_light_fog',
      '3_clear',
      '4_mid_clear',
      '5_light_clouds',
      '6_mid_clouds',
      '7_heavy_clouds',
    ],
    # Apps
    'apps': [
      'Chat',
      'gMeter',
    ],
    # PP Filters
    'ppfilters': [
      'b&w',
      'blue_steel',
      'custom config example',
      'default', 'default_bright',
      'default_dark',
      'movie',
      'natural',
      'photographic',
      'sepia',
      'vintage',
      ],
  },

  # Files present in all versions of CSP
  'csp-common-files': [
    'dwrite.dll',
    ( 'extension',
      [ 'shaders.zip',
        ( 'config',
          [ 'brakedisc_fx.ini', 'car_instruments.ini', 'chaser_camera.ini', 'chat_shortcuts.ini',
            'colorful_shadowing.ini', 'data_alt_mapping.ini', 'data_apps_allowed_to_pause.txt',
            'data_car_classes.ini', 'data_car_years.ini', 'data_countries.ini', 'data_credits.txt',
            'data_gbuffer.ini', 'data_human_materials.ini', 'data_manifest.ini',
            'data_oem_colors_vintage.txt', 'data_standard_content.ini', 'dxgi_tweaks.ini',
            'extra_fx.ini', 'fake_shadows_fx.ini', 'ffb_tweaks.ini', 'freer_camera.ini',
            'g27_lights.ini', 'general.ini', 'graphics_adjustments.ini', 'grass_fx.ini', 'gui.ini',
            'lighting_fx.ini', 'mumble_plugin.ini', 'music.ini', 'neck.ini', 'new_behaviour.ini',
            'nice_screenshots.ini', 'particles_fx.ini', 'reflections_fx.ini', 'shadowed_wheels.ini',
            'skidmarks_fx.ini', 'small_tweaks.ini', 'smart_mirror.ini', 'smart_shadows.ini',
            'splashscreen.ini', 'taskbar.ini', 'track_adjustments.ini', 'triple_custom.ini',
            'tyres_fx.ini', 'vr_tweaks.ini', 'walking_out.ini', 'weather_fx.ini', 'windscreen_fx.ini',
            'yebisest.ini',
            ( 'cars',
              [ ( 'common',
                  [ 'custom_emissive.ini', 'custom_rims.ini', 'dev_material_carpaint.ini',
                    'dev_material_interior.ini', 'f1_generic.ini', 'f1_lights.ini',
                    'f1_tyre_damage.ini', 'functions_base.lua', 'gt3_exhaust_glow.ini',
                    'gt3_lights.ini', 'gt3_tyres_kunos.ini', 'human_surface_template.ini',
                    'materials_base.ini', 'materials_carpaint.ini', 'materials_glass.ini',
                    'materials_interior.ini', 'materials_license_plate.ini', 'navigators.ini',
                    'navigators_layouts.ini', 'navigators_maps.ini', 'navigators_mixins.ini',
                    'navigators_themes.ini', 'no_popup_lights.ini',
                    'oldschool_lights_reflections.ini', 'selflighting.ini', 'tyre_patterns.ini']),
                ('generic', ['generic.ini', 'generic_fixes.ini', 'generic_rain_tyres.ini'])]),
            ( 'tracks',
              [ ( 'common',
                  [ 'all_conditions.ini', 'benner900conditions.ini', 'colorfulness.lut',
                    'colorfulnesspotrero.lut', 'conditions.ini', 'conditions_blm.ini',
                    'custom_emissive.ini', 'digiclock47_conditions.ini', 'flag_colors.lut',
                    'functions_base.lua', 'grass_fx.ini', 'materials_base.ini', 'materials_glass.ini',
                    'materials_track.ini']),
                ('generic', ['generic.ini'])])]),
        ( 'lua',
          [ ( 'chaser-camera',
              [ ('arcade-mode', ['camera.lua', 'manifest.ini']),
                ('arcade-mode-2', ['camera.lua', 'manifest.ini']),
                ('base', ['camera.lua', 'manifest.ini']),
                ('drone', ['camera.lua', 'manifest.ini'])]),
            ( 'fireworks',
              [ ( 'holidays',
                  [ 'extra_fireworks.bank', 'fireworks.lua', 'fireworks_audio.lua',
                    'fireworks_base.lua', 'fireworks_colors.lua', 'fireworks_pyro.lua',
                    'fireworks_schemes.lua', 'fireworks_spawn.lua', 'fireworks_types.lua',
                    'guids.txt', 'manifest.ini', 'utils.lua',
                    ( 'schemes',
                      [ 'christmas.lua', 'debug.lua', 'default.lua', 'independence_day.lua',
                        'victory_day.lua'])])]),
            ( 'new-modes',
              [ ('driver-interview', ['manifest.ini', 'mode.lua', 'stopwatch.png', 'tasks.png']),
                ('overtake', ['manifest.ini', 'mode.lua'])])]),
        ( 'textures',
          [ ( 'color_grading',
              [ '3-strip alt.png', '3-strip.png', 'autumn.png', 'ava.png', 'bright.png',
                'cine bright.png', 'cine cold.png', 'cine drama.png', 'cine teal orange 1.png',
                'cine teal orange 2.png', 'cine vibrant.png', 'cine warm.png', 'coffee.png',
                'crisp winter.png', 'dark blue.png', 'deep.png', 'dithered.png', 'faded.png',
                'four.png', 'fuji 2393.png', 'fuji 3510.png', 'kodak.png', 'moody.png',
                'natural pop.png', 'neutral.png', 'oldschool.png', 'rottenish.png', 'saturated.png',
                'teigen.png', 'the matrix.png', 'threshold.png', 'tweed.png', 'underpass.png'])]),
        ( 'weather',
          [ ( 'base',
              [ 'manifest.ini', 'weather.lua', ('clouds', ['atlas.dds']),
                ( 'src',
                  [ 'conditions_converter.lua', 'consts.lua', 'light_pollution.lua', 'utils.lua',
                    'weather_application.lua', 'weather_clouds.lua',
                    'weather_clouds_pertrack.lua'])])]),
        ('weather-controllers', [('base', ['controller.lua', 'manifest.ini'])])])
  ],
}

# Dictionary functions
def get(key, default=None, /):
  return data.get(key, default)

def items():
  return data.items()

def keys():
  return data.keys()

def values():
  return data.values()
