# Data
data = {
  # Lists of Kunos-made assets
  'kunos-assets': {
    # Cars
    'cars': [
      'abarth500',
      'abarth500_s1',
      'alfa_romeo_giulietta_qv',
      'alfa_romeo_giulietta_qv_le',
      'bmw_1m',
      'bmw_1m_s3',
      'bmw_m3_e30',
      'bmw_m3_e30_drift',
      'bmw_m3_e30_dtm',
      'bmw_m3_e30_gra',
      'bmw_m3_e30_s1',
      'bmw_m3_e92',
      'bmw_m3_e92_drift',
      'bmw_m3_e92_s1',
      'bmw_m3_gt2',
      'bmw_z4',
      'bmw_z4_drift',
      'bmw_z4_gt3',
      'bmw_z4_s1',
      'ferrari_312t',
      'ferrari_458',
      'ferrari_458_gt2',
      'ferrari_458_s3',
      'ferrari_599xxevo',
      'ferrari_f40',
      'ferrari_f40_s3',
      'ferrari_laferrari',
      'ks_abarth500_assetto_corse',
      'ks_abarth_595ss',
      'ks_abarth_595ss_s1',
      'ks_abarth_595ss_s2',
      'ks_alfa_33_stradale',
      'ks_alfa_giulia_qv',
      'ks_alfa_mito_qv',
      'ks_alfa_romeo_155_v6',
      'ks_alfa_romeo_4c',
      'ks_alfa_romeo_gta',
      'ks_audi_a1s1',
      'ks_audi_r18_etron_quattro',
      'ks_audi_r8_lms',
      'ks_audi_r8_lms_2016',
      'ks_audi_r8_plus',
      'ks_audi_sport_quattro',
      'ks_audi_sport_quattro_rally',
      'ks_audi_sport_quattro_s1',
      'ks_audi_tt_cup',
      'ks_audi_tt_vln',
      'ks_bmw_m235i_racing',
      'ks_bmw_m4',
      'ks_bmw_m4_akrapovic',
      'ks_corvette_c7_stingray',
      'ks_corvette_c7r',
      'ks_ferrari_250_gto',
      'ks_ferrari_288_gto',
      'ks_ferrari_312_67',
      'ks_ferrari_330_p4',
      'ks_ferrari_488_challenge_evo',
      'ks_ferrari_488_gt3',
      'ks_ferrari_488_gt3_2020',
      'ks_ferrari_488_gtb',
      'ks_ferrari_812_superfast',
      'ks_ferrari_f138',
      'ks_ferrari_f2004',
      'ks_ferrari_fxx_k',
      'ks_ferrari_sf15t',
      'ks_ferrari_sf70h',
      'ks_ford_escort_mk1',
      'ks_ford_gt40',
      'ks_ford_mustang_2015',
      'ks_glickenhaus_scg003',
      'ks_lamborghini_aventador_sv',
      'ks_lamborghini_countach',
      'ks_lamborghini_countach_s1',
      'ks_lamborghini_gallardo_sl',
      'ks_lamborghini_gallardo_sl_s3',
      'ks_lamborghini_huracan_gt3',
      'ks_lamborghini_huracan_performante',
      'ks_lamborghini_huracan_st',
      'ks_lamborghini_miura_sv',
      'ks_lamborghini_sesto_elemento',
      'ks_lotus_25',
      'ks_lotus_3_eleven',
      'ks_lotus_72d',
      'ks_maserati_250f_12cyl',
      'ks_maserati_250f_6cyl',
      'ks_maserati_alfieri',
      'ks_maserati_gt_mc_gt4',
      'ks_maserati_levante',
      'ks_maserati_mc12_gt1',
      'ks_maserati_quattroporte',
      'ks_mazda_787b',
      'ks_mazda_miata',
      'ks_mazda_mx5_cup',
      'ks_mazda_mx5_nd',
      'ks_mazda_rx7_spirit_r',
      'ks_mazda_rx7_tuned',
      'ks_mclaren_570s',
      'ks_mclaren_650_gt3',
      'ks_mclaren_f1_gtr',
      'ks_mclaren_p1',
      'ks_mclaren_p1_gtr',
      'ks_mercedes_190_evo2',
      'ks_mercedes_amg_gt3',
      'ks_mercedes_c9',
      'ks_nissan_370z',
      'ks_nissan_gtr',
      'ks_nissan_gtr_gt3',
      'ks_nissan_skyline_r34',
      'ks_pagani_huayra_bc',
      'ks_porsche_718_boxster_s',
      'ks_porsche_718_boxster_s_pdk',
      'ks_porsche_718_cayman_s',
      'ks_porsche_718_spyder_rs',
      'ks_porsche_908_lh',
      'ks_porsche_911_carrera_rsr',
      'ks_porsche_911_gt1',
      'ks_porsche_911_gt3_cup_2017',
      'ks_porsche_911_gt3_r_2016',
      'ks_porsche_911_gt3_rs',
      'ks_porsche_911_r',
      'ks_porsche_911_rsr_2017',
      'ks_porsche_917_30',
      'ks_porsche_917_k',
      'ks_porsche_918_spyder',
      'ks_porsche_919_hybrid_2015',
      'ks_porsche_919_hybrid_2016',
      'ks_porsche_935_78_moby_dick',
      'ks_porsche_962c_longtail',
      'ks_porsche_962c_shorttail',
      'ks_porsche_991_carrera_s',
      'ks_porsche_991_turbo_s',
      'ks_porsche_cayenne',
      'ks_porsche_cayman_gt4_clubsport',
      'ks_porsche_cayman_gt4_std',
      'ks_porsche_macan',
      'ks_porsche_panamera',
      'ks_praga_r1',
      'ks_ruf_rt12r',
      'ks_ruf_rt12r_awd',
      'ks_toyota_ae86',
      'ks_toyota_ae86_drift',
      'ks_toyota_ae86_tuned',
      'ks_toyota_celica_st185',
      'ks_toyota_gt86',
      'ks_toyota_supra_mkiv',
      'ks_toyota_supra_mkiv_drift',
      'ks_toyota_supra_mkiv_tuned',
      'ks_toyota_ts040',
      'ktm_xbow_r',
      'lotus_2_eleven',
      'lotus_2_eleven_gt4',
      'lotus_49',
      'lotus_98t',
      'lotus_elise_sc',
      'lotus_elise_sc_s1',
      'lotus_elise_sc_s2',
      'lotus_evora_gtc',
      'lotus_evora_gte',
      'lotus_evora_gte_carbon',
      'lotus_evora_gx',
      'lotus_evora_s',
      'lotus_evora_s_s2',
      'lotus_exige_240',
      'lotus_exige_240_s3',
      'lotus_exige_s',
      'lotus_exige_s_roadster',
      'lotus_exige_scura',
      'lotus_exige_v6_cup',
      'lotus_exos_125',
      'lotus_exos_125_s1',
      'mclaren_mp412c',
      'mclaren_mp412c_gt3',
      'mercedes_sls',
      'mercedes_sls_gt3',
      'p4-5_2011',
      'pagani_huayra',
      'pagani_zonda_r',
      'ruf_yellowbird',
      'shelby_cobra_427sc',
      'tatuusfa1',
    ],
    # Tracks
    'tracks': [
      'drift',
      'imola',
      'ks_barcelona',
      'ks_black_cat_county',
      'ks_brands_hatch',
      'ks_drag',
      'ks_highlands',
      'ks_laguna_seca',
      'ks_monza66',
      'ks_nordschleife',
      'ks_nurburgring',
      'ks_red_bull_ring',
      'ks_silverstone',
      'ks_silverstone1967',
      'ks_vallelunga',
      'ks_zandvoort',
      'magione',
      'monza',
      'mugello',
      'spa',
      'trento-bondone',
    ],
    # Weather
    'weather': [
      '1_heavy_fog',
      '2_light_fog',
      '3_clear',
      '4_mid_clear',
      '5_light_clouds',
      '6_mid_clouds',
      '7_heavy_clouds',
    ],
    # Apps
    'apps': [
      'Chat',
      'gMeter',
    ],
    # PP Filters
    'ppfilters': [
      'b&w',
      'blue_steel',
      'custom config example',
      'default', 'default_bright',
      'default_dark',
      'movie',
      'natural',
      'photographic',
      'sepia',
      'vintage',
      ],
  },

  # Files present in all versions of CSP
  'csp-common-files': [
    'dwrite.dll',
    ( 'extension',
      [ 'shaders.zip',
        ( 'config',
          [ 'brakedisc_fx.ini', 'car_instruments.ini', 'chaser_camera.ini', 'chat_shortcuts.ini',
            'colorful_shadowing.ini', 'data_alt_mapping.ini', 'data_apps_allowed_to_pause.txt',
            'data_car_classes.ini', 'data_car_years.ini', 'data_countries.ini', 'data_credits.txt',
            'data_gbuffer.ini', 'data_human_materials.ini', 'data_manifest.ini',
            'data_oem_colors_vintage.txt', 'data_standard_content.ini', 'dxgi_tweaks.ini',
            'extra_fx.ini', 'fake_shadows_fx.ini', 'ffb_tweaks.ini', 'freer_camera.ini',
            'g27_lights.ini', 'general.ini', 'graphics_adjustments.ini', 'grass_fx.ini', 'gui.ini',
            'lighting_fx.ini', 'mumble_plugin.ini', 'music.ini', 'neck.ini', 'new_behaviour.ini',
            'nice_screenshots.ini', 'particles_fx.ini', 'reflections_fx.ini', 'shadowed_wheels.ini',
            'skidmarks_fx.ini', 'small_tweaks.ini', 'smart_mirror.ini', 'smart_shadows.ini',
            'splashscreen.ini', 'taskbar.ini', 'track_adjustments.ini', 'triple_custom.ini',
            'tyres_fx.ini', 'vr_tweaks.ini', 'walking_out.ini', 'weather_fx.ini', 'windscreen_fx.ini',
            'yebisest.ini',
            ( 'cars',
              [ ( 'common',
                  [ 'custom_emissive.ini', 'custom_rims.ini', 'dev_material_carpaint.ini',
                    'dev_material_interior.ini', 'f1_generic.ini', 'f1_lights.ini',
                    'f1_tyre_damage.ini', 'functions_base.lua', 'gt3_exhaust_glow.ini',
                    'gt3_lights.ini', 'gt3_tyres_kunos.ini', 'human_surface_template.ini',
                    'materials_base.ini', 'materials_carpaint.ini', 'materials_glass.ini',
                    'materials_interior.ini', 'materials_license_plate.ini', 'navigators.ini',
                    'navigators_layouts.ini', 'navigators_maps.ini', 'navigators_mixins.ini',
                    'navigators_themes.ini', 'no_popup_lights.ini',
                    'oldschool_lights_reflections.ini', 'selflighting.ini', 'tyre_patterns.ini']),
                ('generic', ['generic.ini', 'generic_fixes.ini', 'generic_rain_tyres.ini'])]),
            ( 'tracks',
              [ ( 'common',
                  [ 'all_conditions.ini', 'benner900conditions.ini', 'colorfulness.lut',
                    'colorfulnesspotrero.lut', 'conditions.ini', 'conditions_blm.ini',
                    'custom_emissive.ini', 'digiclock47_conditions.ini', 'flag_colors.lut',
                    'functions_base.lua', 'grass_fx.ini', 'materials_base.ini', 'materials_glass.ini',
                    'materials_track.ini']),
                ('generic', ['generic.ini'])])]),
        ( 'lua',
          [ ( 'chaser-camera',
              [ ('arcade-mode', ['camera.lua', 'manifest.ini']),
                ('arcade-mode-2', ['camera.lua', 'manifest.ini']),
                ('base', ['camera.lua', 'manifest.ini']),
                ('drone', ['camera.lua', 'manifest.ini'])]),
            ( 'fireworks',
              [ ( 'holidays',
                  [ 'extra_fireworks.bank', 'fireworks.lua', 'fireworks_audio.lua',
                    'fireworks_base.lua', 'fireworks_colors.lua', 'fireworks_pyro.lua',
                    'fireworks_schemes.lua', 'fireworks_spawn.lua', 'fireworks_types.lua',
                    'guids.txt', 'manifest.ini', 'utils.lua',
                    ( 'schemes',
                      [ 'christmas.lua', 'debug.lua', 'default.lua', 'independence_day.lua',
                        'victory_day.lua'])])]),
            ( 'new-modes',
              [ ('driver-interview', ['manifest.ini', 'mode.lua', 'stopwatch.png', 'tasks.png']),
                ('overtake', ['manifest.ini', 'mode.lua'])])]),
        ( 'textures',
          [ ( 'color_grading',
              [ '3-strip alt.png', '3-strip.png', 'autumn.png', 'ava.png', 'bright.png',
                'cine bright.png', 'cine cold.png', 'cine drama.png', 'cine teal orange 1.png',
                'cine teal orange 2.png', 'cine vibrant.png', 'cine warm.png', 'coffee.png',
                'crisp winter.png', 'dark blue.png', 'deep.png', 'dithered.png', 'faded.png',
                'four.png', 'fuji 2393.png', 'fuji 3510.png', 'kodak.png', 'moody.png',
                'natural pop.png', 'neutral.png', 'oldschool.png', 'rottenish.png', 'saturated.png',
                'teigen.png', 'the matrix.png', 'threshold.png', 'tweed.png', 'underpass.png'])]),
        ( 'weather',
          [ ( 'base',
              [ 'manifest.ini', 'weather.lua', ('clouds', ['atlas.dds']),
                ( 'src',
                  [ 'conditions_converter.lua', 'consts.lua', 'light_pollution.lua', 'utils.lua',
                    'weather_application.lua', 'weather_clouds.lua',
                    'weather_clouds_pertrack.lua'])])]),
        ('weather-controllers', [('base', ['controller.lua', 'manifest.ini'])])])
  ],
  # Files present in all versions of Pure
  'pure-common-files': [
    ( 'apps',
      [ ( 'lua',
          [ ( 'pureconfig',
              [ '_license and copyright.txt', 'icon.png', 'manifest.ini', 'pureconfig.lua',
                ('ui', ['configdesign.lua', 'configinfo.lua'])])])]),
    ( 'content',
      [ ('gui', [('icons', ['sol planner_off.png', 'sol planner_on.png'])]),
        ( 'weather',
          [ ('sol_00_no_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_01_clear', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_02_few_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_03_scattered_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_04_windy', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_05_broken_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_06_overcast', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_11_mist', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_12_fog', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_21_haze', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_22_dust', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_23_sand', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_24_smoke', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_31_light_drizzle', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_32_drizzle', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_33_heavy_drizzle', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_34_light_rain', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_35_rain', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_36_heavy_rain', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_41_light_thunderstorm', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_42_thunderstorm', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_43_heavy_thunderstorm', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_44_squalls', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_45_tornado', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_46_hurricane', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_51_light_snow', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_52_snow', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_53_heavy_snow', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_54_light_sleet', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_55_sleet', ['preview.jpg', 'weather.ini']),
            ('sol_56_heavy_sleet', ['preview.jpg', 'weather.ini']),
            ('sol_57_hail', ['preview.jpg', 'weather.ini'])])]),
    ( 'extension',
      [ ( 'config-ext',
          [ ( 'pure',
              [ ( 'skydome_sets',
                  [ ( 'default_16k',
                      [ 'skydome_script.lua',
                        ( 'textures',
                          [ '159534903_mask.dds', '159534903n_mask.dds', '160889919_mask.dds',
                            '160889920_mask.dds', '161184986_mask.dds', '161568492n_mask.dds',
                            '162072753_mask.dds', '162700796_mask.dds', '163266525_mask.dds',
                            '165516231_mask.dds', '171898272_mask.dds', '174645428_mask.dds',
                            '176525931_mask.dds', '176525936_mask.dds', '178602682_mask.dds',
                            '178602682n_mask.dds', '179611287_mask.dds', '180258644_mask.dds',
                            '180258667_mask.dds', '180909074_mask.dds', '180909084_mask.dds',
                            '181447523_mask.dds', '182453668_mask.dds', '183249460_mask.dds',
                            '183249480_mask.dds', '188756621_mask.dds', '190692927_mask.dds',
                            '190760457_mask.dds', '190760457n_mask.dds', '192150758_mask.dds',
                            '196200727_mask.dds', '196200739_mask.dds', '217529345_mask.dds',
                            '228834139_mask.dds', '231158888_mask.dds', '233525913_mask.dds',
                            '235922208_mask.dds', '235922208n_mask.dds', '240377153_mask.dds',
                            '242498123_mask.dds',
                            ( 'encrypted',
                              [ '159534903.dds', '159534903n.dds', '160889919.dds', '160889920.dds',
                                '161184986.dds', '161568492.dds', '161568492n.dds', '162072753.dds',
                                '162700796.dds', '163266525.dds', '165516231.dds', '171898272.dds',
                                '174645428.dds', '176525931.dds', '176525936.dds', '178602682.dds',
                                '178602682n.dds', '179611287.dds', '180258644.dds', '180258667.dds',
                                '180909074.dds', '180909084.dds', '181447523.dds', '182453668.dds',
                                '183249430.dds', '183249460.dds', '183249480.dds', '188756621.dds',
                                '190692927.dds', '190760457.dds', '190760457n.dds', '192150758.dds',
                                '196200727.dds', '196200739.dds', '217529345.dds', '228834139.dds',
                                '231158888.dds', '233525913.dds', '235922208.dds', '235922208n.dds',
                                '240377153.dds', '242498123.dds'])])])])])]),
        ( 'weather',
          [ ( 'pure',
              [ '_license and copyright.txt', 'manifest.ini', 'pure_ai.lua', 'pure_audio.lua',
                'pure_camera.lua', 'pure_config.lua', 'pure_globals.lua', 'pure_interface.lua',
                'pure_planner.lua', 'pure_pp.lua', 'pure_raw.lua', 'pure_render.lua',
                'pure_script.lua', 'pure_sharing.lua', 'pure_state.lua', 'pure_stellar.lua',
                'pure_track.lua', 'pure_weather.lua', 'pure_world.lua', 'weather.lua',
                ('audio', ['guids.txt', 'rain.bank', 'sol.bank', 'wiper.bank']),
                ('config', ['config_classes.lua']), ('exposure', ['pure_exposure.lua']),
                ('pp', ['tonemapping.fx', 'tonemapping.lua']),
                ( 'render',
                  [ 'render__list.lua',
                    ( 'landscape',
                      [ 'noise3d.dds', 'render_landscape.lua_encrypted',
                        ( 'textures',
                          [ 'asian-city-farm-dark-forest.dds', 'asian-city-full.dds',
                            'asian-city-w-forest.dds', 'austr-city-farm1-mixed-forest2.dds',
                            'austr-city-farm1.dds', 'euro-city-farmgreen-mixed-forest.dds',
                            'european-city-on-farm-1.dds', 'european-farm-1.dds', 'farm-mixed-2.dds',
                            'forest-dark-eurofarm-brown-v2.dds', 'forest-decidious-barren-land-1.dds',
                            'forest-decidious-eurofarm-1-v2.dds', 'forest-mixed-western-barren-2.dds',
                            'french-farm-sparsecity-1.dds', 'grand-canyon-red-3.dds',
                            'grand-canyon-red-4.dds', 'grand-canyon-red-5.dds',
                            'grand-canyon-red-trees.dds', 'mntn-red-desert.dds',
                            'range-herbacious-bare-ground-2.dds', 'range-herbacious-grass-green.dds',
                            'range-herbacious-grass-yellow.dds',
                            'range-herbacious-mixed-wilderness-3.dds', 'source.txt'])]),
                    ( 'rainhaze',
                      [ 'noise3d.dds', 'rainhaze_apply.fx', 'rainhaze_base.fx',
                        'render_rainhaze.lua'])]),
                ( 'script',
                  ['default_exposure_handling.lua', 'post_processing.lua', 'script_tools.lua']),
                ('sdk', ['pure_sdk.lua']), ('space', ['moon.png', 'starmap_8k.dds']),
                ('track_adaptions', ['track_adaption.ini']),
                ('ui', ['pure_ui.lua', 'pure_ui__filedialog.lua']),
                ( 'utils',
                  [ 'config_ini_parser.lua', 'json_parser.lua', 'utils_basics.lua',
                    'utils_connect.lua', 'utils_csp_backwards_compatibility.lua', 'utils_dataset.lua',
                    'utils_json.lua', 'utils_lua.lua', 'utils_lut.lua', 'utils_memory_backup.lua',
                    'utils_stack.lua', 'utils_state.lua', 'utils_wrongcsp.lua']),
                ('weather', ['weather_definitions.json', 'weather_definitions.lua']),
                ( 'world',
                  [ 'world_ambient_light.lua', 'world_clouds.lua',
                    'world_directional_ambient_light.lua', 'world_fog.lua', 'world_lights.lua',
                    'world_moon.lua', 'world_night_light_pollution.lua', 'world_sky.lua',
                    'world_sun_light.lua',
                    ( 'clouds',
                      [ ( '2d',
                          [ 'class_set.lua', 'class_texture.lua', 'class_weather.lua',
                            'clouds_main.lua']),
                        ( '3d',
                          [ 'cloud_definitions.lua', 'clouds_cirrostratus.lua', 'clouds_classes.lua',
                            'clouds_cumulus.lua', 'clouds_general_lighting.lua',
                            'clouds_lightnings.lua', 'clouds_main.lua', 'clouds_shadows.lua',
                            ( 'textures',
                              [ 'c1.png', 'c2.dds', 'c2.png', 'c3.dds', 'c3.png', 'c4.dds', 'c4.png',
                                'c5.png', 'c6.png', 'c_b1.dds', 'c_b1.png', 'debug_honly.png',
                                'debug_hv.png', 'debug_vonly.png'])])]),
                    ('lightnings', ['lightnings.lua', 'lightnings_classes.lua'])])])]),
        ('weather-controllers', [])]),
    ( 'system',
      [ ( 'cfg',
          [ ( 'ppfilters',
              [ 'pure.ini', 'purecandy.ini', 'purelinear.ini',
                ( 'pure_scripts',
                  [ 'default_script.lua', 'pure.lua', 'pure_nopp.lua', 'purecandy.lua',
                    'purelinear.lua'])])])])
  ],
  # All files that have ever been in any version of Pure
  'pure-all-files': [
    '_license and copyright.txt', 'description.jsgme', 'install_pure.bat', 'uninstall_pure.bat',
    'uninstall_sol.bat', 'uninstall_sol__install_pure.bat',
    ( 'apps',
      [ ( 'lua',
          [ ( 'pureconfig',
              [ '_license and copyright.txt', 'icon.png', 'manifest.ini', 'pureconfig.lua',
                'reset_dummy.lua',
                ('ui', ['configdesign.lua', 'configinfo.lua', 'gl.lua', ('assets', ['strobo.png'])]),
                ('utils', ['fix_settings.lua', 'groundfog.lua'])]),
            ( 'pureplanner',
              [ '_license and copyright.txt', 'ext_app_controls.ini', 'icon.png', 'manifest.ini',
                'pureplanner.lua', 'reset_dummy.lua',
                ('classes', ['connect_dummy.lua', 'container.lua']),
                ('connection', ['controller.lua', 'extended_controls.lua', 'states.lua']),
                ( 'help',
                  [ 'pure_planner.txt', 'pure_planner_chinese.txt', 'pure_planner_deutsch.txt',
                    'pure_planner_dutch.txt', 'pure_planner_espania.txt', 'pure_planner_francais.txt',
                    ( 'editor',
                      [ 'data_slider_basic.png', 'data_slider_range.png', 'transition_basic.png',
                        'transition_clear_rain.png', 'weather_selection_cm.png',
                        'weather_selection_random.png']),
                    ('live', ['live_control.png']), ('main', []),
                    ('settings', ['save_button.png'])]),
                ( 'plan',
                  [ 'live.lua', 'location.lua', 'plan.lua', 'plan_manager.lua', 'stellar.lua',
                    'time_handling.lua', 'weather.lua', 'weather_dynamic.lua', 'weather_live.lua']),
                ('settings', ['settings.lua', 'settings_defaults.lua']),
                ( 'ui',
                  [ 'gl.lua', 'plannerdesign.lua', 'tools.lua', 'ui_globals.lua',
                    ( 'assets',
                      [ ('control', ['timemulti_backward.png', 'timemulti_forward.png']),
                        ('controller', ['arrow-0.png', 'arrow-45.png']),
                        ( 'stellar',
                          [ 'iss.png', 'mars.png', 'mercury.png', 'moon0.png', 'moon1.png',
                            'moon2.png', 'moon3.png', 'moon4.png', 'moon5.png', 'moon6.png',
                            'moon7.png', 'moon8.png', 'moon9.png', 'saturn.png', 'sun.png',
                            'venus.png']),
                        ( 'weather',
                          [ '0.png', '1.png', '10.png', '100.png', '11.png', '12.png', '13.png',
                            '14.png', '15.png', '16.png', '17.png', '18.png', '19.png', '2.png',
                            '20.png', '21.png', '22.png', '23.png', '24.png', '25.png', '26.png',
                            '27.png', '28.png', '3.png', '31.png', '4.png', '40.png', '41.png',
                            '42.png', '5.png', '50.png', '6.png', '666.png', '7.png', '8.png',
                            '9.png', 'override.png'])])])]),
            ( 'purepp',
              [ '_license and copyright.txt', 'icon.png', 'manifest.ini', 'purepp.lua',
                'reset_dummy.lua', ('ui', ['gl.lua', 'ppdesign.lua']),
                ('utils', ['fix_settings.lua', 'groundfog.lua'])])]),
        ( 'python',
          [ ( 'sol_planner',
              [ 'sol_planner.ini', 'sol_planner.py',
                ( 'plans',
                  [ 'clouds_test.ini', 'cloudy-rainy-nice.ini', 'cm-test.ini', 'empty.ini',
                    'lemans21test.ini', 'random dry.ini', 'summer-day.ini', 'test4.ini']),
                ( 'presets',
                  [ '__backup2.ini', 'backup1.ini', 'bad45.ini', 'checker123weathersuite.ini',
                    'clear.ini', 'crazy.ini', 'dry.ini', 'empty.ini', 'export.ini', 'exporttest4.ini',
                    'more presets with unusable settings and many more unrelated stuff.ini',
                    'one.ini', 'only sun.ini', 'presets.ini', 'test1.ini', 'test123.ini',
                    'test345.ini', 'two.ini', 'ultranice.ini', 'unpredictable.ini']),
                ('settings', ['settings.ini', 'settings_defaults.ini']),
                ( 'sol_lib',
                  [ 'down.png', 'sol_dialogs.py', 'sol_interface.py', 'sol_stellar.py', 'sol_ui.py',
                    'up.png']),
                ('stdlib', ['_ctypes.pyd']), ('stdlib64', ['_ctypes.pyd']),
                ( 'tex',
                  [ '0.png', '1.png', '10.png', '100.png', '11.png', '12.png', '13.png', '14.png',
                    '15.png', '16.png', '17.png', '18.png', '19.png', '2.png', '20.png', '21.png',
                    '22.png', '23.png', '24.png', '25.png', '26.png', '27.png', '28.png', '3.png',
                    '31.png', '4.png', '40.png', '41.png', '42.png', '5.png', '50.png', '6.png',
                    '666.png', '7.png', '8.png', '9.png', 'exportplan.png', 'exportpreset.png',
                    'fullday.png', 'importplan.png', 'importpreset.png', 'minus.png', 'moon0.png',
                    'moon1.png', 'moon2.png', 'moon3.png', 'moon4.png', 'moon5.png', 'moon6.png',
                    'pause.png', 'play.png', 'plus.png', 'repeat.png', 'stamped.png', 'stop.png',
                    'sun.png', 'time-minus.png', 'time-plus.png', 'timed.png']),
                ('ui', ['ui_app.json'])])])]),
    ( 'content',
      [ ('gui', [('icons', ['sol planner_off.png', 'sol planner_on.png'])]),
        ( 'weather',
          [ ('sol_00_no_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_01_clear', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_02_few_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_03_scattered_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_04_windy', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_05_broken_clouds', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_06_overcast', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_11_mist', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_12_fog', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_21_haze', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_22_dust', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_23_sand', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_24_smoke', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_31_light_drizzle', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_32_drizzle', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_33_heavy_drizzle', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_34_light_rain', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_35_rain', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_36_heavy_rain', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_41_light_thunderstorm', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_42_thunderstorm', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_43_heavy_thunderstorm', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_44_squalls', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_45_tornado', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_46_hurricane', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_51_light_snow', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_52_snow', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_53_heavy_snow', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_54_light_sleet', ['colorcurves.ini', 'preview.jpg', 'weather.ini']),
            ('sol_55_sleet', ['preview.jpg', 'weather.ini']),
            ('sol_56_heavy_sleet', ['preview.jpg', 'weather.ini']),
            ('sol_57_hail', ['preview.jpg', 'weather.ini'])])]),
    ( 'extension',
      [ ( 'config-ext',
          [ ( 'pure',
              [ ('custom_track_adaptions', []),
                ( 'skydome_sets',
                  [ ( 'default_16k',
                      [ 'skydome_script.lua', 'skydome_script_lcs.lua',
                        ( 'textures',
                          [ '159534776_mask.dds', '159534903_mask.dds', '159534903n_mask.dds',
                            '159678489_mask.dds', '159678490_mask.dds', '159678491_mask.dds',
                            '160889919_mask.dds', '160889920_mask.dds', '161184986_mask.dds',
                            '161568492_mask.dds', '161568492n_mask.dds', '162072753_mask.dds',
                            '162700796_mask.dds', '162700797_mask.dds', '163266525.dds',
                            '163266525_mask.dds', '164102245_mask.dds', '165516231_mask.dds',
                            '166498827_mask.dds', '166498828_mask.dds', '171898272_mask.dds',
                            '174645428_mask.dds', '176525931_mask.dds', '176525936_mask.dds',
                            '178602682_mask.dds', '178602682n_mask.dds', '179611287_mask.dds',
                            '180258644_mask.dds', '180258667_mask.dds', '180909074_mask.dds',
                            '180909084_mask.dds', '181447523_mask.dds', '182453668_mask.dds',
                            '183249430_mask.dds', '183249448_mask.dds', '183249460_mask.dds',
                            '183249480_mask.dds', '185704534_mask.dds', '187739154_mask.dds',
                            '188756621_mask.dds', '190692927_mask.dds', '190760432_mask.dds',
                            '190760457_mask.dds', '190760457n_mask.dds', '192150758_mask.dds',
                            '196200727_mask.dds', '196200739_mask.dds', '199053995_mask.dds',
                            '217529345_mask.dds', '228834139_mask.dds', '231158888_mask.dds',
                            '233525898_mask.dds', '233525913_mask.dds', '235922208_mask.dds',
                            '235922208n_mask.dds', '240377143_mask.dds', '240377153_mask.dds',
                            '242498123_mask.dds', '256406606_mask.dds',
                            'copyright and source information of the.pdf',
                            'copyright and source information.pdf',
                            ( 'encrypted',
                              [ '159534776.dds', '159534903.dds', '159534903n.dds', '159678489.dds',
                                '159678490.dds', '159678491.dds', '160889919.dds', '160889920.dds',
                                '161184986.dds', '161568492.dds', '161568492n.dds', '162072753.dds',
                                '162700796.dds', '162700797.dds', '163266525.dds', '164102245.dds',
                                '165516231.dds', '166498827.dds', '166498828.dds', '171898272.dds',
                                '174645428.dds', '176525931.dds', '176525936.dds', '178602682.dds',
                                '178602682n.dds', '179611287.dds', '180258644.dds', '180258667.dds',
                                '180909074.dds', '180909084.dds', '181447523.dds', '182453668.dds',
                                '183249430.dds', '183249448.dds', '183249460.dds', '183249480.dds',
                                '185704534.dds', '187739154.dds', '188756621.dds', '190692927.dds',
                                '190760432.dds', '190760457.dds', '190760457n.dds', '192150758.dds',
                                '196200727.dds', '196200739.dds', '199053995.dds', '217529345.dds',
                                '228834139.dds', '231158888.dds', '233525898.dds', '233525913.dds',
                                '235922208.dds', '235922208n.dds', '240377143.dds', '240377153.dds',
                                '242498123.dds', '256406606.dds',
                                'copyright and source information of the.pdf',
                                'copyright and source information.pdf'])])])])]),
            ( 'pureplanner',
              [('plans', [('daycycle', []), ('stamp', []), ('timed', [])]), ('weatherpresets', [])]),
            ('pureshaders', [])]),
        ('lua', [('pp-filters', [('pure', ['filter.lua', 'manifest.ini', 'reset_dummy.lua'])])]),
        ( 'weather',
          [ ( 'pure',
              [ '_license and copyright.txt', 'manifest.ini', 'pure lcs.code-workspace',
                'pure_ai.lua', 'pure_audio.lua', 'pure_camera.lua', 'pure_config.lua',
                'pure_globals.lua', 'pure_interface.lua', 'pure_planner.lua', 'pure_pp.lua',
                'pure_ppstate.lua', 'pure_raw.lua', 'pure_render.lua', 'pure_script.lua',
                'pure_sharing.lua', 'pure_state.lua', 'pure_stellar.lua', 'pure_track.lua',
                'pure_weather.lua', 'pure_world.lua', 'reset_dummy.lua', 'settings.ini',
                'weather.lua',
                ( 'audio',
                  [ '__sol.bank', 'csp_base_audio.lua', 'guids.txt', 'rain.bank', 'sol.bank',
                    'wiper.bank']),
                ('config', ['config_classes.lua']), ('exposure', ['pure_exposure.lua']),
                ( 'pp',
                  [ 'blur_prepare.fx', 'custom_filters.lua', 'custompp.fx', 'postprocessing.hlsl',
                    'postprocessing.lua', 'tonemapping.fx', 'tonemapping.lua',
                    ( 'yebis',
                      [ 'pp_blur_prepare.fx', 'pp_dof.fx', 'pp_final.fx', 'pp_gamma.fx',
                        'pp_tonemapping.hlsl'])]),
                ('ppf_scripts', []),
                ( 'render',
                  [ 'render__list.lua',
                    ( 'groundfog',
                      [ 'groundfog_area.fx', 'groundfog_spline.fx', 'noise3d.dds',
                        'render_groundfog.lua', 'settings_groundfog_eco.lua', 'smoke3d - source.txt',
                        'smoke3d.dds']),
                    ( 'landscape',
                      [ 'noise3d.dds', 'render_landscape.lua_encrypted',
                        ( 'backup',
                          [ 'landscape.fx', 'noise3d.dds', 'render_landscape.lua',
                            'render_landscape.lua_encrypted']),
                        ( 'textures',
                          [ 'asian-city-farm-dark-forest.dds', 'asian-city-full.dds',
                            'asian-city-w-forest.dds', 'austr-city-farm1-mixed-forest2.dds',
                            'austr-city-farm1.dds', 'euro-city-farmgreen-mixed-forest.dds',
                            'european-city-on-farm-1.dds', 'european-farm-1.dds', 'farm-mixed-2.dds',
                            'forest-dark-eurofarm-brown-v2.dds', 'forest-decidious-barren-land-1.dds',
                            'forest-decidious-eurofarm-1-v2.dds', 'forest-mixed-western-barren-2.dds',
                            'french-farm-sparsecity-1.dds', 'grand-canyon-red-3.dds',
                            'grand-canyon-red-4.dds', 'grand-canyon-red-5.dds',
                            'grand-canyon-red-trees.dds', 'mntn-red-desert.dds',
                            'range-herbacious-bare-ground-2.dds', 'range-herbacious-grass-green.dds',
                            'range-herbacious-grass-yellow.dds',
                            'range-herbacious-mixed-wilderness-3.dds', 'source.txt',
                            'water-ocean.dds'])]),
                    ( 'lightning',
                      [ 'hdr.fx', 'lightning.fx', 'noise3d.dds', 'render_lightning.lua',
                        'settings_lightning_eco.lua', 'testpic.png']),
                    ( 'rainhaze',
                      [ 'noise3d.dds', 'rainhaze_apply.fx', 'rainhaze_base.fx',
                        'render_rainhaze.lua']),
                    ( 'sunblinding',
                      [ 'blur.fx', 'blur_fine.fx', 'blurrgba.fx', 'burn.fx', 'depth_check.fx',
                        'hdr.fx', 'mask.fx', 'merge.fx', 'mergergba.fx', 'noise3d.dds',
                        'render_sunblinding.lua', 'settings_sunblinding_eco.lua'])]),
                ( 'script',
                  ['default_exposure_handling.lua', 'post_processing.lua', 'script_tools.lua']),
                ('sdk', ['pure sdk - import this in your workspace.lua', 'pure_sdk.lua']),
                ('server', ['pureplanneronlineconverter.lua']),
                ('space', ['moon.dds', 'moon.png', 'starmap_8k.dds']),
                ( 'spice',
                  [ 'gl.lua', 'spice.lua',
                    ( 'spice_hdr_effects',
                      [ 'calibration.hlsl', 'colorgrading.hlsl', 'magicbloom.hlsl', 'magicbloom.lua',
                        'sensornoise.hlsl', 'shadertools.hlsl', 'speedtunnel.hlsl', 'speedtunnel.lua',
                        'spice_hdr.fx', ('colorgrading', ['neutral.png'])]),
                    ( 'spice_ldr_effects',
                      [ 'blacklevel.png', 'calibration.hlsl', 'curvedscreen.fx', 'curvedscreen.hlsl',
                        'curvedscreen.lua', 'curvedscreen.png', 'filter.lua', 'overlay.hlsl',
                        'overlay.lua', 'shadertools.hlsl', 'spice_ldr.fx', 'testoverlay.png',
                        'whitelevel.png'])]),
                ('textures', ['horizont.png', 'overcast.png', 'skydome_dummy.dds']),
                ( 'track_adaptions',
                  [ 'track_adaption.ini',
                    ( 'groundfog',
                      [ 'groundfog___ks_red_bull_ring_layout_gp.json',
                        'groundfog_fonteny_fonteny.json',
                        'groundfog_ks_ad_scottish_highlands_layout_int.json',
                        'groundfog_ks_brands_hatch_gp.json', 'groundfog_ks_brands_hatch_indy.json',
                        'groundfog_ks_highlands_layout_drift.json',
                        'groundfog_ks_highlands_layout_int.json',
                        'groundfog_ks_highlands_layout_int_traf_left.json',
                        'groundfog_ks_highlands_layout_int_traf_right.json',
                        'groundfog_ks_highlands_layout_long.json', 'groundfog_ks_laguna_seca_.json',
                        'groundfog_ks_nordschleife_endurance.json',
                        'groundfog_ks_nordschleife_nordschleife.json',
                        'groundfog_ks_red_bull_ring_layout_gp.json', 'groundfog_monza_.json',
                        'groundfog_mugello_.json', 'groundfog_spa_.json', 'groundfog_spa_2022.json',
                        'groundfog_tajo_abtraffic.json', 'groundfog_tmp.json',
                        'groundfog_union_island_scenic.json', 'groundfog_union_island_traffic.json',
                        'groundfog_union_island_west.json', 'groundfog_vir_full course.json'])]),
                ('ui', ['pure_ui.lua', 'pure_ui__filedialog.lua', 'pure_ui_help.lua']),
                ( 'utils',
                  [ 'config_ini_parser.lua', 'json_parser.lua', 'utils_basics.lua',
                    'utils_connect.lua', 'utils_cpu.lua', 'utils_csp_backwards_compatibility.lua',
                    'utils_dataset.lua', 'utils_import.json', 'utils_import.lua', 'utils_json.lua',
                    'utils_lua.lua', 'utils_lut.lua', 'utils_memory_backup.lua',
                    'utils_smoothing.lua', 'utils_stack.lua', 'utils_state.lua',
                    'utils_wrongcsp.lua']),
                ('weather', ['weather_definitions.json', 'weather_definitions.lua']),
                ( 'world',
                  [ 'world_ambient_light.lua', 'world_clouds.lua',
                    'world_directional_ambient_light.lua', 'world_fog.lua',
                    'world_fog__gamma_fix.lua', 'world_lights.lua', 'world_moon.lua',
                    'world_night_light_pollution.lua', 'world_sky.lua', 'world_sun_light.lua',
                    ( 'clouds',
                      [ ( '2d',
                          [ 'bottom.fx', 'class_set.lua', 'class_texture.lua', 'class_weather.lua',
                            'clouds_main.lua']),
                        ( '3d',
                          [ 'cloud_definitions.lua', 'clouds_cirrostratus.lua', 'clouds_classes.lua',
                            'clouds_cumulus.lua', 'clouds_general_lighting.lua',
                            'clouds_lightnings.lua', 'clouds_main.lua', 'clouds_shadows.lua',
                            ( 'textures',
                              [ 'c1.png', 'c2.dds', 'c2.png', 'c3.dds', 'c3.png', 'c4.dds', 'c4.png',
                                'c5.png', 'c6.png', 'c_b1.dds', 'c_b1.png', 'debug_honly.png',
                                'debug_hv.png', 'debug_vonly.png'])])]),
                    ('fog_classes', ['pure_fog_classes.lua']),
                    ('lightnings', ['lightnings.lua', 'lightnings_classes.lua'])])]),
            ( 'pure lcs',
              [ '_license and copyright.txt', 'forced_settings.ini', 'manifest.ini', 'moon.dds',
                'moon_enc.dds', 'moon_end.dds', 'reset_dummy.lua', 'settings.ini', 'spice233.zip',
                'weather.lua', ('.vscode', ['settings.json']),
                ('clouds', ['atlas.dds', 'iw_d26.dds', 'noise3d.dds']),
                ('ppf_scripts', ['default_script.lua', 'pure_nopp.lua']),
                ( 'pure',
                  [ 'pure_ai.lua', 'pure_audio.lua', 'pure_camera.lua', 'pure_exposure.lua',
                    'pure_globals.lua', 'pure_header.lua', 'pure_pp.lua', 'pure_ppstate.lua',
                    'pure_render.lua', 'pure_script.lua', 'pure_sharing.lua', 'pure_state.lua',
                    'pure_track.lua', 'pure_update.lua', ('audio', ['csp_base_audio.lua']),
                    ( 'config',
                      [ 'config_classes.lua', 'pure_config.lua', 'pure_config_root.lua',
                        'pure_config_tools.lua']),
                    ('osd', ['osd_class.lua', 'pureosds.lua']),
                    ( 'pp',
                      [ 'custom_filters.lua', 'postprocessing.lua', 'tonemapping.fx',
                        'tonemapping.lua', 'tonemapping_lightpp.fx']),
                    ( 'render',
                      [ 'render__list.lua',
                        ( 'groundfog',
                          [ 'groundfog_area.fx', 'groundfog_headlights.fx', 'groundfog_spline.fx',
                            'highbeams.dds', 'noise3d.dds', 'render_groundfog.lua',
                            'settings_groundfog_eco.lua', 'smoke3d - source.txt', 'smoke3d.dds']),
                        ('landscape', ['landscape_quad.fx', 'render_landscape.lua']),
                        ( 'lightning',
                          [ 'hdr.fx', 'lightning.fx', 'noise3d.dds', 'render_lightning.lua',
                            'settings_lightning_eco.lua', 'testpic.png']),
                        ( 'mountains',
                          [ 'cloud.fx', 'noise3d.dds', 'render_mountains.lua', 'test8.dds',
                            'worley7.dds']),
                        ( 'rainhaze',
                          [ 'noise3d.dds', 'rainhaze_apply.fx', 'rainhaze_base.fx',
                            'render_rainhaze.lua']),
                        ('sunblinding', ['render_sunblinding.lua', 'settings_sunblinding_eco.lua'])]),
                    ( 'script',
                      ['default_exposure_handling.lua', 'post_processing.lua', 'script_tools.lua']),
                    ('sdk', ['pure sdk - import this in your workspace.lua', 'pure_sdk.lua']),
                    ('space', ['moon.dds', 'starmap_8k.dds']),
                    ( 'utils',
                      [ 'config_ini_parser.lua', 'gl.lua', 'json_parser.lua', 'utils_basics.lua',
                        'utils_connect.lua', 'utils_cpu.lua', 'utils_header.lua', 'utils_import.json',
                        'utils_json.lua', 'utils_lut.lua', 'utils_memory_backup.lua',
                        'utils_smoothing.lua', 'utils_state.lua', 'utils_wrongcsp.lua']),
                    ( 'world',
                      [ 'world_clouds.lua',
                        ( 'clouds',
                          [ ( '2d',
                              [ 'bottom.fx', 'class_set.lua', 'class_texture.lua',
                                'class_weather.lua', 'clouds_main.lua',
                                ('textures', ['skydome_dummy.dds'])]),
                            ( '3d',
                              [ 'clouds_classes.lua', 'clouds_main.lua', 'clouds_shadows.lua',
                                ('textures', ['c2.dds', 'c_b1.dds'])]),
                            ( 'skydomes',
                              [ 'cloud_shadows.fx', 'clouds__skydomes.lua',
                                'clouds__skydomes_shadows.lua', 'test.png'])]),
                        ('lightnings', ['lightnings.lua', 'lightnings_classes.lua'])])]),
                ( 'shaders',
                  [ 'aurora_apply.fx', 'aurora_base.hlsl', 'aurora_blur.fx', 'aurora_blur_high.fx',
                    'aurora_shape.fx', 'aurora_shape_high.fx', 'cloud_shadows_test.fx', 'clouds.fx',
                    'fog.fx', 'lightning.fx', 'pp_ae_1.fx', 'pp_ae_pure_prepare.fx',
                    'pp_bloom_downsample.fx', 'pp_bloom_quality1.fx', 'pp_bloom_threshold.fx',
                    'pp_bloom_upsample.fx', 'pp_blur_prepare copy.fx', 'pp_blur_prepare.fx',
                    'pp_dof.fx', 'pp_final.fx', 'pp_gamma.fx', 'pp_tonemapping.hlsl',
                    'rainhaze_apply.fx', 'rainhaze_base.fx', 'showroom_cubemap.fx', 'surface.fx',
                    'test.fx', 'tonemapping_test.fx']),
                ( 'spice',
                  [ 'gl.lua', 'spice.lua',
                    ( 'spice_hdr_effects',
                      [ 'calibration.hlsl', 'colorgrading.hlsl', 'magicbloom.hlsl', 'magicbloom.lua',
                        'sensornoise.hlsl', 'shadertools.hlsl', 'speedtunnel.hlsl', 'speedtunnel.lua',
                        'spice_hdr.fx', ('colorgrading', ['neutral.png'])]),
                    ( 'spice_ldr_effects',
                      [ 'blacklevel.png', 'calibration.hlsl', 'curvedscreen.fx', 'curvedscreen.hlsl',
                        'curvedscreen.lua', 'curvedscreen.png', 'filter.lua', 'overlay.hlsl',
                        'overlay.lua', 'shadertools.hlsl', 'spice_ldr.fx', 'testoverlay.png',
                        'whitelevel.png'])]),
                ( 'src',
                  [ 'audio.lua', 'conditions_converter.lua', 'consts.lua', 'light_pollution.lua',
                    'render.lua', 'render_aurora.lua', 'render_clouds.lua', 'render_eclipse.lua',
                    'render_fog.lua', 'render_lightning.lua', 'render_linear.lua',
                    'render_meteor.lua', 'render_postprocessing.lua', 'render_rain.lua',
                    'render_surface.lua', 'render_test.lua', 'showroom_mode.lua', 'tests.lua',
                    'utils.lua', 'weather_application.lua', 'weather_clouds.lua',
                    'weather_clouds_pertrack.lua', 'weather_clouds_types.lua'])])]),
        ( 'weather-controllers',
          [ ( 'purectrl',
              [ 'cm-drive.lua', 'controller.lua', 'manifest.ini', 'settings.ini',
                'weather_params.lua', ('.vscode', ['settings.json'])]),
            ('purectrl static', ['controller.lua', 'manifest.ini']),
            ( 'sol2',
              [ 'cm-drive.lua', 'controller.lua', 'manifest.ini', 'reset_dummy.lua', 'settings.ini',
                'sol__interface.lua', 'sol__shared_memory__backup.lua', 'tools.lua', 'utils_lut.lua',
                'weather_params.lua']),
            ('sol2static', ['controller.lua', 'manifest.ini'])])]),
    ( 'system',
      [ ( 'cfg',
          [ ( 'ppfilters',
              [ 'pure.ini', 'purecandy.ini', 'purehdr-eye.ini', 'purehdr.ini', 'purelinear.ini',
                'puresimple.ini', 'purevr.ini',
                ( 'pure_scripts',
                  [ 'default_script.lua', 'pure.lua', 'pure_nopp.lua', 'purecandy.lua',
                    'purehdr-eye.lua', 'purehdr.lua', 'purelinear.lua', 'purevr.lua',
                    ('pure_ui', ['pure.ui', 'purebg.png', 'purelogo.png'])]),
                ( 'purelcs_scripts',
                  [ 'pure.lua', 'purecandy.lua', 'purehdr.lua', 'purelinear.lua', 'purevr.lua',
                    ('pure', ['purelcs_hdr.lua', 'purelcs_screen.lua', 'purelcs_vr.lua']),
                    ('pure_ui', ['pure.ui', 'purebg.png', 'purelogo.png'])])])])])
  ],
}

# Dictionary functions
def get(key, default=None, /):
  return data.get(key, default)

def items():
  return data.items()

def keys():
  return data.keys()

def values():
  return data.values()
