# Data
data = {

  # Paths
  ## Asset path suffixes
  'asset-dirs': {
    'cars':      ['content', 'cars'],
    'tracks':    ['content', 'tracks'],
    'apps':      ['apps'],
    'ppfilters': ['system', 'cfg', 'ppfilters'],
    'weather':   ['content', 'weather'],
  },

  # Lists of Kunos-made assets
  'kunos-assets': {
    # Cars
    'cars': [
      'abarth500',
      'abarth500_s1',
      'alfa_romeo_giulietta_qv',
      'alfa_romeo_giulietta_qv_le',
      'bmw_1m',
      'bmw_1m_s3',
      'bmw_m3_e30',
      'bmw_m3_e30_drift',
      'bmw_m3_e30_dtm',
      'bmw_m3_e30_gra',
      'bmw_m3_e30_s1',
      'bmw_m3_e92',
      'bmw_m3_e92_drift',
      'bmw_m3_e92_s1',
      'bmw_m3_gt2',
      'bmw_z4',
      'bmw_z4_drift',
      'bmw_z4_gt3',
      'bmw_z4_s1',
      'ferrari_312t',
      'ferrari_458',
      'ferrari_458_gt2',
      'ferrari_458_s3',
      'ferrari_599xxevo',
      'ferrari_f40',
      'ferrari_f40_s3',
      'ferrari_laferrari',
      'ks_abarth500_assetto_corse',
      'ks_abarth_595ss',
      'ks_abarth_595ss_s1',
      'ks_abarth_595ss_s2',
      'ks_alfa_33_stradale',
      'ks_alfa_giulia_qv',
      'ks_alfa_mito_qv',
      'ks_alfa_romeo_155_v6',
      'ks_alfa_romeo_4c',
      'ks_alfa_romeo_gta',
      'ks_audi_a1s1',
      'ks_audi_r18_etron_quattro',
      'ks_audi_r8_lms',
      'ks_audi_r8_lms_2016',
      'ks_audi_r8_plus',
      'ks_audi_sport_quattro',
      'ks_audi_sport_quattro_rally',
      'ks_audi_sport_quattro_s1',
      'ks_audi_tt_cup',
      'ks_audi_tt_vln',
      'ks_bmw_m235i_racing',
      'ks_bmw_m4',
      'ks_bmw_m4_akrapovic',
      'ks_corvette_c7_stingray',
      'ks_corvette_c7r',
      'ks_ferrari_250_gto',
      'ks_ferrari_288_gto',
      'ks_ferrari_312_67',
      'ks_ferrari_330_p4',
      'ks_ferrari_488_challenge_evo',
      'ks_ferrari_488_gt3',
      'ks_ferrari_488_gt3_2020',
      'ks_ferrari_488_gtb',
      'ks_ferrari_812_superfast',
      'ks_ferrari_f138',
      'ks_ferrari_f2004',
      'ks_ferrari_fxx_k',
      'ks_ferrari_sf15t',
      'ks_ferrari_sf70h',
      'ks_ford_escort_mk1',
      'ks_ford_gt40',
      'ks_ford_mustang_2015',
      'ks_glickenhaus_scg003',
      'ks_lamborghini_aventador_sv',
      'ks_lamborghini_countach',
      'ks_lamborghini_countach_s1',
      'ks_lamborghini_gallardo_sl',
      'ks_lamborghini_gallardo_sl_s3',
      'ks_lamborghini_huracan_gt3',
      'ks_lamborghini_huracan_performante',
      'ks_lamborghini_huracan_st',
      'ks_lamborghini_miura_sv',
      'ks_lamborghini_sesto_elemento',
      'ks_lotus_25',
      'ks_lotus_3_eleven',
      'ks_lotus_72d',
      'ks_maserati_250f_12cyl',
      'ks_maserati_250f_6cyl',
      'ks_maserati_alfieri',
      'ks_maserati_gt_mc_gt4',
      'ks_maserati_levante',
      'ks_maserati_mc12_gt1',
      'ks_maserati_quattroporte',
      'ks_mazda_787b',
      'ks_mazda_miata',
      'ks_mazda_mx5_cup',
      'ks_mazda_mx5_nd',
      'ks_mazda_rx7_spirit_r',
      'ks_mazda_rx7_tuned',
      'ks_mclaren_570s',
      'ks_mclaren_650_gt3',
      'ks_mclaren_f1_gtr',
      'ks_mclaren_p1',
      'ks_mclaren_p1_gtr',
      'ks_mercedes_190_evo2',
      'ks_mercedes_amg_gt3',
      'ks_mercedes_c9',
      'ks_nissan_370z',
      'ks_nissan_gtr',
      'ks_nissan_gtr_gt3',
      'ks_nissan_skyline_r34',
      'ks_pagani_huayra_bc',
      'ks_porsche_718_boxster_s',
      'ks_porsche_718_boxster_s_pdk',
      'ks_porsche_718_cayman_s',
      'ks_porsche_718_spyder_rs',
      'ks_porsche_908_lh',
      'ks_porsche_911_carrera_rsr',
      'ks_porsche_911_gt1',
      'ks_porsche_911_gt3_cup_2017',
      'ks_porsche_911_gt3_r_2016',
      'ks_porsche_911_gt3_rs',
      'ks_porsche_911_r',
      'ks_porsche_911_rsr_2017',
      'ks_porsche_917_30',
      'ks_porsche_917_k',
      'ks_porsche_918_spyder',
      'ks_porsche_919_hybrid_2015',
      'ks_porsche_919_hybrid_2016',
      'ks_porsche_935_78_moby_dick',
      'ks_porsche_962c_longtail',
      'ks_porsche_962c_shorttail',
      'ks_porsche_991_carrera_s',
      'ks_porsche_991_turbo_s',
      'ks_porsche_cayenne',
      'ks_porsche_cayman_gt4_clubsport',
      'ks_porsche_cayman_gt4_std',
      'ks_porsche_macan',
      'ks_porsche_panamera',
      'ks_praga_r1',
      'ks_ruf_rt12r',
      'ks_ruf_rt12r_awd',
      'ks_toyota_ae86',
      'ks_toyota_ae86_drift',
      'ks_toyota_ae86_tuned',
      'ks_toyota_celica_st185',
      'ks_toyota_gt86',
      'ks_toyota_supra_mkiv',
      'ks_toyota_supra_mkiv_drift',
      'ks_toyota_supra_mkiv_tuned',
      'ks_toyota_ts040',
      'ktm_xbow_r',
      'lotus_2_eleven',
      'lotus_2_eleven_gt4',
      'lotus_49',
      'lotus_98t',
      'lotus_elise_sc',
      'lotus_elise_sc_s1',
      'lotus_elise_sc_s2',
      'lotus_evora_gtc',
      'lotus_evora_gte',
      'lotus_evora_gte_carbon',
      'lotus_evora_gx',
      'lotus_evora_s',
      'lotus_evora_s_s2',
      'lotus_exige_240',
      'lotus_exige_240_s3',
      'lotus_exige_s',
      'lotus_exige_s_roadster',
      'lotus_exige_scura',
      'lotus_exige_v6_cup',
      'lotus_exos_125',
      'lotus_exos_125_s1',
      'mclaren_mp412c',
      'mclaren_mp412c_gt3',
      'mercedes_sls',
      'mercedes_sls_gt3',
      'p4-5_2011',
      'pagani_huayra',
      'pagani_zonda_r',
      'ruf_yellowbird',
      'shelby_cobra_427sc',
      'tatuusfa1',
    ],
    # Tracks
    'tracks': [
      'drift',
      'imola',
      'ks_barcelona',
      'ks_black_cat_county',
      'ks_brands_hatch',
      'ks_drag',
      'ks_highlands',
      'ks_laguna_seca',
      'ks_monza66',
      'ks_nordschleife',
      'ks_nurburgring',
      'ks_red_bull_ring',
      'ks_silverstone',
      'ks_silverstone1967',
      'ks_vallelunga',
      'ks_zandvoort',
      'magione',
      'monza',
      'mugello',
      'spa',
      'trento-bondone',
    ],
    # PP Filters
    'ppfilters': ['b&w', 'blue_steel', 'custom config example', 'default', 'default_bright', 'default_dark', 'movie', 'natural', 'photographic', 'sepia', 'vintage'],
    # Weather
    'weather': ['1_heavy_fog', '2_light_fog', '3_clear', '4_mid_clear', '5_light_clouds', '6_mid_clouds', '7_heavy_clouds'],
    # Apps
    'apps': ['Chat', 'gMeter', 'system'],
  },

  # CSP related data
  'csp': {
    # Files present in all versions of CSP
    'common-dirs': [
      ['extension'],
      ['extension', 'config'],
      ['extension', 'config', 'cars'],
      ['extension', 'config', 'cars', 'common'],
      ['extension', 'config', 'cars', 'generic'],
      ['extension', 'config', 'tracks'],
      ['extension', 'config', 'tracks', 'common'],
      ['extension', 'config', 'tracks', 'generic'],
      ['extension', 'lua'],
      ['extension', 'lua', 'chaser-camera'],
      ['extension', 'lua', 'chaser-camera', 'arcade-mode'],
      ['extension', 'lua', 'chaser-camera', 'arcade-mode-2'],
      ['extension', 'lua', 'chaser-camera', 'base'],
      ['extension', 'lua', 'chaser-camera', 'drone'],
      ['extension', 'lua', 'fireworks'],
      ['extension', 'lua', 'fireworks', 'holidays'],
      ['extension', 'lua', 'fireworks', 'holidays', 'schemes'],
      ['extension', 'lua', 'new-modes'],
      ['extension', 'lua', 'new-modes', 'driver-interview'],
      ['extension', 'lua', 'new-modes', 'overtake'],
      ['extension', 'textures'],
      ['extension', 'textures', 'color_grading'],
      ['extension', 'weather'],
      ['extension', 'weather-controllers'],
      ['extension', 'weather-controllers', 'base'],
      ['extension', 'weather', 'base'],
      ['extension', 'weather', 'base', 'clouds'],
      ['extension', 'weather', 'base', 'src']
    ],
    'common-files': [
      ['dwrite.dll'],
      ['extension', 'config', 'brakedisc_fx.ini'],
      ['extension', 'config', 'car_instruments.ini'],
      ['extension', 'config', 'cars', 'common', 'custom_emissive.ini'],
      ['extension', 'config', 'cars', 'common', 'custom_rims.ini'],
      ['extension', 'config', 'cars', 'common', 'dev_material_carpaint.ini'],
      ['extension', 'config', 'cars', 'common', 'dev_material_interior.ini'],
      ['extension', 'config', 'cars', 'common', 'f1_generic.ini'],
      ['extension', 'config', 'cars', 'common', 'f1_lights.ini'],
      ['extension', 'config', 'cars', 'common', 'f1_tyre_damage.ini'],
      ['extension', 'config', 'cars', 'common', 'functions_base.lua'],
      ['extension', 'config', 'cars', 'common', 'gt3_exhaust_glow.ini'],
      ['extension', 'config', 'cars', 'common', 'gt3_lights.ini'],
      ['extension', 'config', 'cars', 'common', 'gt3_tyres_kunos.ini'],
      ['extension', 'config', 'cars', 'common', 'human_surface_template.ini'],
      ['extension', 'config', 'cars', 'common', 'materials_base.ini'],
      ['extension', 'config', 'cars', 'common', 'materials_carpaint.ini'],
      ['extension', 'config', 'cars', 'common', 'materials_glass.ini'],
      ['extension', 'config', 'cars', 'common', 'materials_interior.ini'],
      ['extension', 'config', 'cars', 'common', 'materials_license_plate.ini'],
      ['extension', 'config', 'cars', 'common', 'navigators.ini'],
      ['extension', 'config', 'cars', 'common', 'navigators_layouts.ini'],
      ['extension', 'config', 'cars', 'common', 'navigators_maps.ini'],
      ['extension', 'config', 'cars', 'common', 'navigators_mixins.ini'],
      ['extension', 'config', 'cars', 'common', 'navigators_themes.ini'],
      ['extension', 'config', 'cars', 'common', 'no_popup_lights.ini'],
      ['extension', 'config', 'cars', 'common', 'oldschool_lights_reflections.ini'],
      ['extension', 'config', 'cars', 'common', 'selflighting.ini'],
      ['extension', 'config', 'cars', 'common', 'tyre_patterns.ini'],
      ['extension', 'config', 'cars', 'generic', 'generic.ini'],
      ['extension', 'config', 'cars', 'generic', 'generic_fixes.ini'],
      ['extension', 'config', 'cars', 'generic', 'generic_rain_tyres.ini'],
      ['extension', 'config', 'chaser_camera.ini'],
      ['extension', 'config', 'chat_shortcuts.ini'],
      ['extension', 'config', 'colorful_shadowing.ini'],
      ['extension', 'config', 'data_alt_mapping.ini'],
      ['extension', 'config', 'data_apps_allowed_to_pause.txt'],
      ['extension', 'config', 'data_car_classes.ini'],
      ['extension', 'config', 'data_car_years.ini'],
      ['extension', 'config', 'data_countries.ini'],
      ['extension', 'config', 'data_credits.txt'],
      ['extension', 'config', 'data_gbuffer.ini'],
      ['extension', 'config', 'data_human_materials.ini'],
      ['extension', 'config', 'data_manifest.ini'],
      ['extension', 'config', 'data_oem_colors_vintage.txt'],
      ['extension', 'config', 'data_standard_content.ini'],
      ['extension', 'config', 'dxgi_tweaks.ini'],
      ['extension', 'config', 'extra_fx.ini'],
      ['extension', 'config', 'fake_shadows_fx.ini'],
      ['extension', 'config', 'ffb_tweaks.ini'],
      ['extension', 'config', 'freer_camera.ini'],
      ['extension', 'config', 'g27_lights.ini'],
      ['extension', 'config', 'general.ini'],
      ['extension', 'config', 'graphics_adjustments.ini'],
      ['extension', 'config', 'grass_fx.ini'],
      ['extension', 'config', 'gui.ini'],
      ['extension', 'config', 'lighting_fx.ini'],
      ['extension', 'config', 'mumble_plugin.ini'],
      ['extension', 'config', 'music.ini'],
      ['extension', 'config', 'neck.ini'],
      ['extension', 'config', 'new_behaviour.ini'],
      ['extension', 'config', 'nice_screenshots.ini'],
      ['extension', 'config', 'particles_fx.ini'],
      ['extension', 'config', 'reflections_fx.ini'],
      ['extension', 'config', 'shadowed_wheels.ini'],
      ['extension', 'config', 'skidmarks_fx.ini'],
      ['extension', 'config', 'small_tweaks.ini'],
      ['extension', 'config', 'smart_mirror.ini'],
      ['extension', 'config', 'smart_shadows.ini'],
      ['extension', 'config', 'splashscreen.ini'],
      ['extension', 'config', 'taskbar.ini'],
      ['extension', 'config', 'track_adjustments.ini'],
      ['extension', 'config', 'tracks', 'common', 'Benner900conditions.ini'],
      ['extension', 'config', 'tracks', 'common', 'all_conditions.ini'],
      ['extension', 'config', 'tracks', 'common', 'colorfulness.lut'],
      ['extension', 'config', 'tracks', 'common', 'colorfulnesspotrero.lut'],
      ['extension', 'config', 'tracks', 'common', 'conditions.ini'],
      ['extension', 'config', 'tracks', 'common', 'conditions_blm.ini'],
      ['extension', 'config', 'tracks', 'common', 'custom_emissive.ini'],
      ['extension', 'config', 'tracks', 'common', 'digiclock47_conditions.ini'],
      ['extension', 'config', 'tracks', 'common', 'flag_colors.lut'],
      ['extension', 'config', 'tracks', 'common', 'functions_base.lua'],
      ['extension', 'config', 'tracks', 'common', 'grass_fx.ini'],
      ['extension', 'config', 'tracks', 'common', 'materials_base.ini'],
      ['extension', 'config', 'tracks', 'common', 'materials_glass.ini'],
      ['extension', 'config', 'tracks', 'common', 'materials_track.ini'],
      ['extension', 'config', 'tracks', 'generic', 'generic.ini'],
      ['extension', 'config', 'triple_custom.ini'],
      ['extension', 'config', 'tyres_fx.ini'],
      ['extension', 'config', 'vr_tweaks.ini'],
      ['extension', 'config', 'walking_out.ini'],
      ['extension', 'config', 'weather_fx.ini'],
      ['extension', 'config', 'windscreen_fx.ini'],
      ['extension', 'config', 'yebisest.ini'],
      ['extension', 'lua', 'chaser-camera', 'arcade-mode-2', 'camera.lua'],
      ['extension', 'lua', 'chaser-camera', 'arcade-mode-2', 'manifest.ini'],
      ['extension', 'lua', 'chaser-camera', 'arcade-mode', 'camera.lua'],
      ['extension', 'lua', 'chaser-camera', 'arcade-mode', 'manifest.ini'],
      ['extension', 'lua', 'chaser-camera', 'base', 'camera.lua'],
      ['extension', 'lua', 'chaser-camera', 'base', 'manifest.ini'],
      ['extension', 'lua', 'chaser-camera', 'drone', 'camera.lua'],
      ['extension', 'lua', 'chaser-camera', 'drone', 'manifest.ini'],
      ['extension', 'lua', 'fireworks', 'holidays', 'GUIDs.txt'],
      ['extension', 'lua', 'fireworks', 'holidays', 'extra_fireworks.bank'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks_audio.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks_base.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks_colors.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks_pyro.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks_schemes.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks_spawn.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'fireworks_types.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'manifest.ini'],
      ['extension', 'lua', 'fireworks', 'holidays', 'schemes', 'christmas.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'schemes', 'debug.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'schemes', 'default.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'schemes', 'independence_day.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'schemes', 'victory_day.lua'],
      ['extension', 'lua', 'fireworks', 'holidays', 'utils.lua'],
      ['extension', 'lua', 'new-modes', 'driver-interview', 'manifest.ini'],
      ['extension', 'lua', 'new-modes', 'driver-interview', 'mode.lua'],
      ['extension', 'lua', 'new-modes', 'driver-interview', 'stopwatch.png'],
      ['extension', 'lua', 'new-modes', 'driver-interview', 'tasks.png'],
      ['extension', 'lua', 'new-modes', 'overtake', 'manifest.ini'],
      ['extension', 'lua', 'new-modes', 'overtake', 'mode.lua'],
      ['extension', 'shaders.zip'],
      ['extension', 'textures', 'color_grading', '3-strip Alt.png'],
      ['extension', 'textures', 'color_grading', '3-strip.png'],
      ['extension', 'textures', 'color_grading', 'Autumn.png'],
      ['extension', 'textures', 'color_grading', 'Ava.png'],
      ['extension', 'textures', 'color_grading', 'Bright.png'],
      ['extension', 'textures', 'color_grading', 'Cine Bright.png'],
      ['extension', 'textures', 'color_grading', 'Cine Cold.png'],
      ['extension', 'textures', 'color_grading', 'Cine Drama.png'],
      ['extension', 'textures', 'color_grading', 'Cine Teal Orange 1.png'],
      ['extension', 'textures', 'color_grading', 'Cine Teal Orange 2.png'],
      ['extension', 'textures', 'color_grading', 'Cine Vibrant.png'],
      ['extension', 'textures', 'color_grading', 'Cine Warm.png'],
      ['extension', 'textures', 'color_grading', 'Coffee.png'],
      ['extension', 'textures', 'color_grading', 'Crisp Winter.png'],
      ['extension', 'textures', 'color_grading', 'Dark Blue.png'],
      ['extension', 'textures', 'color_grading', 'Deep.png'],
      ['extension', 'textures', 'color_grading', 'Dithered.png'],
      ['extension', 'textures', 'color_grading', 'Faded.png'],
      ['extension', 'textures', 'color_grading', 'Four.png'],
      ['extension', 'textures', 'color_grading', 'Fuji 2393.png'],
      ['extension', 'textures', 'color_grading', 'Fuji 3510.png'],
      ['extension', 'textures', 'color_grading', 'Kodak.png'],
      ['extension', 'textures', 'color_grading', 'Moody.png'],
      ['extension', 'textures', 'color_grading', 'Natural Pop.png'],
      ['extension', 'textures', 'color_grading', 'Neutral.png'],
      ['extension', 'textures', 'color_grading', 'Oldschool.png'],
      ['extension', 'textures', 'color_grading', 'Rottenish.png'],
      ['extension', 'textures', 'color_grading', 'Saturated.png'],
      ['extension', 'textures', 'color_grading', 'Teigen.png'],
      ['extension', 'textures', 'color_grading', 'The Matrix.png'],
      ['extension', 'textures', 'color_grading', 'Threshold.png'],
      ['extension', 'textures', 'color_grading', 'Tweed.png'],
      ['extension', 'textures', 'color_grading', 'Underpass.png'],
      ['extension', 'weather-controllers', 'base', 'controller.lua'],
      ['extension', 'weather-controllers', 'base', 'manifest.ini'],
      ['extension', 'weather', 'base', 'clouds', 'atlas.dds'],
      ['extension', 'weather', 'base', 'manifest.ini'],
      ['extension', 'weather', 'base', 'src', 'conditions_converter.lua'],
      ['extension', 'weather', 'base', 'src', 'consts.lua'],
      ['extension', 'weather', 'base', 'src', 'light_pollution.lua'],
      ['extension', 'weather', 'base', 'src', 'utils.lua'],
      ['extension', 'weather', 'base', 'src', 'weather_application.lua'],
      ['extension', 'weather', 'base', 'src', 'weather_clouds.lua'],
      ['extension', 'weather', 'base', 'src', 'weather_clouds_pertrack.lua'],
      ['extension', 'weather', 'base', 'weather.lua']
    ],

  }
}

# Dictionary functions
def get(key, default=None, /):
  return data.get(key, default)

def items():
  return data.items()

def keys():
  return data.keys()

def values():
  return data.values()
